// Derived from frontend/src/document/Part_6_Browser_Internals_Web_APIs_Master_Handbook.md (Module 12 — WebSockets & SSE).
// Auto-generated by a one-off parser script from the handbook's per-question template
// (Question, Execution/Flow, Advanced Production Example, Performance/Security Notes,
// Best Practices, Advantages/Disadvantages, Common Mistakes/Interview Traps, Senior
// Follow-up Questions, Related Topics).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Netflix",
  "Adobe",
  "Atlassian",
  "Stripe",
  "Uber",
  "Flipkart",
  "Zoho"
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "jsbrowser-m12-186",
    number: "JSBROWSER-M12-186",
    title: "WebSocket protocol",
    difficulty: "Easy",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket protocol** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket protocol**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket protocol: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket protocol: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket protocol** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket protocol**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-187",
    number: "JSBROWSER-M12-187",
    title: "WebSocket lifecycle",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket lifecycle** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket lifecycle**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket lifecycle: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket lifecycle: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket lifecycle** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket lifecycle**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-188",
    number: "JSBROWSER-M12-188",
    title: "WebSocket reconnect",
    difficulty: "Hard",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket reconnect** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket reconnect**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket reconnect: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket reconnect: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket reconnect** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket reconnect**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-189",
    number: "JSBROWSER-M12-189",
    title: "WebSocket heartbeat",
    difficulty: "Easy",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket heartbeat** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket heartbeat**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket heartbeat: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket heartbeat: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket heartbeat** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket heartbeat**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-190",
    number: "JSBROWSER-M12-190",
    title: "WebSocket backpressure",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket backpressure** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket backpressure**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket backpressure: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket backpressure: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket backpressure** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket backpressure**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-191",
    number: "JSBROWSER-M12-191",
    title: "Server-Sent Events",
    difficulty: "Hard",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **Server-Sent Events** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **Server-Sent Events**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for Server-Sent Events: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: each server event is delivered asynchronously.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for Server-Sent Events: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **Server-Sent Events** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **Server-Sent Events**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-192",
    number: "JSBROWSER-M12-192",
    title: "SSE lifecycle",
    difficulty: "Easy",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **SSE lifecycle** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **SSE lifecycle**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for SSE lifecycle: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: each server event is delivered asynchronously.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for SSE lifecycle: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **SSE lifecycle** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **SSE lifecycle**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-193",
    number: "JSBROWSER-M12-193",
    title: "SSE reconnection",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **SSE reconnection** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **SSE reconnection**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for SSE reconnection: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: each server event is delivered asynchronously.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for SSE reconnection: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **SSE reconnection** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **SSE reconnection**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-194",
    number: "JSBROWSER-M12-194",
    title: "WebSocket vs SSE",
    difficulty: "Hard",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **WebSocket vs SSE** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **WebSocket vs SSE**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for WebSocket vs SSE: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\nConnection-dependent: the message is logged after the socket opens and the server sends data.\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for WebSocket vs SSE: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **WebSocket vs SSE** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **WebSocket vs SSE**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---"],
  },
  {
    id: "jsbrowser-m12-195",
    number: "JSBROWSER-M12-195",
    title: "Real-time frontend architecture",
    difficulty: "Easy",
    experienceLevel: "2–5 Years",
    category: "WebSockets & SSE",
    expectedAnswer: "Explain **Real-time frontend architecture** from a browser-engine and production frontend perspective. What happens internally, why does it matter, and when should a senior engineer choose or avoid it?",
    deepExplanation: "Execution flow: The application invokes or triggers **Real-time frontend architecture**. → The browser validates the relevant document, origin, permission or lifecycle state. → The responsible browser subsystem performs the operation. → The result is delivered synchronously or through an asynchronous callback/event. → Any DOM, network, storage, rendering or memory consequences become observable.\n\nProduction pattern:\n\n```js\n// Production rule for Real-time frontend architecture: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```\n\nExpected output:\n\n```text\n42\n```\n\nPerformance: Avoid unnecessary main-thread work. Measure before optimizing with Performance, Network and Memory tooling. Batch DOM reads/writes when layout work is involved. Use caching, streaming, lazy loading and resource hints when they match the workload. Consider memory retention and cleanup for listeners, observers, workers and long-lived resources.\n\nSecurity: Respect the Same-Origin Policy, CORS, CSP, secure contexts, permissions, cookie attributes and iframe isolation. Never treat client-side checks as a replacement for server authorization.",
    productionExample: "```js\n// Production rule for Real-time frontend architecture: isolate the capability behind a small boundary.\nexport function useBrowserCapability() {\n  if (typeof window === \"undefined\") return false;\n  return true;\n}\n```",
    bestPractices: ["Encapsulate **Real-time frontend architecture** behind a small application boundary.","Feature-detect where appropriate.","Handle failure and unsupported environments.","Instrument production-critical behavior.","Clean up listeners, observers, workers and resources."],
    tradeOffs: "Advantages: Standardized browser capability when broadly supported.; Can improve user experience, performance or reliability when used appropriately.. Disadvantages: Browser support and policy restrictions vary.; Some APIs require secure contexts, permissions or user activation.; Poor usage can increase memory, CPU, network or rendering cost..",
    commonMistakes: ["Assuming all browsers implement an API identically.","Ignoring security policies.","Performing expensive work on the main thread.","Forgetting lifecycle cleanup.","Optimizing without measurement.","Interview trap: Confusing browser APIs with ECMAScript language features.","Interview trap: Saying that every callback is a macrotask without considering the specific scheduling mechanism.","Interview trap: Treating the DOM, render tree and CSSOM as the same structure.","Interview trap: Claiming that `localStorage` is suitable for sensitive authentication secrets."],
    followUpQuestions: ["What is the browser's internal cost of **Real-time frontend architecture**?","Which work happens on the main thread?","Which lifecycle or security restrictions apply?","How would Chrome DevTools expose the behavior?","What changes across Chrome, Firefox, Safari and Edge?","How would you design a production abstraction around it?"],
    relatedTopics: ["DOM","CSSOM","Rendering Pipeline","Event Loop","Network","Storage","Security","Performance","DevTools","Browser Compatibility","---","# Module 13 – Browser Security","**Questions 196–210**"],
  },
];

export const MOCK_BROWSER_INTERNALS_MODULE12_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
