// Derived from frontend/src/document/DSA_Master_Handbook_Senior_Frontend_Engineers.md (Module 14 — Two Pointers).
// Auto-generated by a one-off parser script from the handbook's per-topic template
// (Definition, JavaScript/TypeScript implementation, Time/Space Complexity,
// Trade-offs, Common Mistakes, Interview Tricks, Interview Questions).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  'Google',
  'Meta',
  'Amazon',
  'Microsoft',
  'Apple',
  'Netflix',
  'Uber',
  'Airbnb',
  'Atlassian',
  'Adobe',
  'LinkedIn',
  'Flipkart',
  'Zoho',
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};

const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "dsa-m14-131",
    number: "DSA-M14-131",
    title: "Opposite-direction pointers",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Opposite-direction pointers start at both ends of a sequence and move toward the center. They work especially well on sorted arrays or when one boundary choice can be ruled out using a monotonic comparison.",
    deepExplanation: "Step 1 — Example: check whether a sorted array is a palindrome-like symmetric sequence.\n\nWITHOUT BUILT-IN / CORE:\n```ts\nfunction isSymmetric(nums: readonly number[]): boolean {\n  let left = 0;\n  let right = nums.length - 1;\n\n  while (left < right) {\n    if (nums[left] !== nums[right]) return false;\n\n    left++;\n    right--;\n  }\n\n  return true;\n}\n```\n\nWITH BUILT-IN:\n```ts\nfunction isSymmetricUsingBuiltIns(nums: readonly number[]): boolean {\n  return nums.every((value, index) =>\n    value === nums[nums.length - 1 - index]\n  );\n}\n```\n\nStep 2 — Example:\n[1,2,3,2,1]\nleft=0/right=4 → 1=1\nleft=1/right=3 → 2=2\n→ true.\n\nStep 3 — Pointer rule:\nAfter comparing the outer pair, both pointers move inward because those positions are fully resolved.\n\nStep 4 — Complexity:\nCore O(n) time, O(1) auxiliary space.",
    productionExample: "Opposite-end pointers are common in sorted searches, palindrome checks, pair-sum problems, collision/interval comparisons, and array validation utilities.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Only move a pointer when the current comparison proves the eliminated region cannot contain the needed answer."],
    tradeOffs: "| Approach | Benefit | Cost |\n|---|---|---|\n| Two pointers | O(n), O(1) extra | Requires useful ordering/symmetry |\n| Hashing | Often handles unsorted input | Extra memory |\n| Brute force | Easy baseline | Usually O(n²) |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?"],
    relatedTopics: ["Two Pointers", "Sorted Arrays", "Palindromes", "Symmetry"],
  },
  {
    id: "dsa-m14-132",
    number: "DSA-M14-132",
    title: "Same-direction pointers",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Same-direction pointers both move from left to right, usually maintaining a write/slow pointer and a read/fast pointer. This is useful for compacting, filtering, deduplicating, and partitioning arrays while preserving relative order.",
    deepExplanation: "Step 1 — Example: move all non-zero values forward in place.\n\nWITHOUT BUILT-IN / CORE:\n```ts\nfunction moveZeros(nums: number[]): void {\n  let write = 0;\n\n  for (let read = 0; read < nums.length; read++) {\n    if (nums[read] === 0) continue;\n\n    [nums[write], nums[read]] = [nums[read]!, nums[write]!];\n    write++;\n  }\n}\n```\n\nWITH BUILT-IN:\n```ts\nfunction moveZerosUsingFilter(nums: readonly number[]): number[] {\n  const nonZero = nums.filter((value) => value !== 0);\n  const zeros = nums.filter((value) => value === 0);\n  return [...nonZero, ...zeros];\n}\n```\n\nStep 2 — Example:\n[0,1,0,3,12]\n→ [1,3,12,0,0].\n\nStep 3 — Invariant:\nAt every step, indexes before `write` already contain the correct non-zero prefix.\n\nStep 4 — Complexity:\nIn-place version O(n) time, O(1) auxiliary space.\nFilter version O(n) time and O(n) extra space.",
    productionExample: "Same-direction pointers are useful for compaction, filtering, stable in-place transforms, removing unwanted elements, and writing processed records into a compact buffer.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Use a slow pointer for the next write position and a fast pointer for scanning input."],
    tradeOffs: "| Approach | Benefit | Cost |\n|---|---|---|\n| Slow/fast pointers | O(1) extra, often stable | More mutation logic |\n| filter/map | Readable | Extra arrays |\n| New result array | Simple and immutable | More memory |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?"],
    relatedTopics: ["Two Pointers", "In-place Algorithms", "Array Compaction", "Filtering"],
  },
  {
    id: "dsa-m14-133",
    number: "DSA-M14-133",
    title: "Two Sum in sorted data",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "For a sorted array, use one pointer at each end. If the sum is too small, move left forward; if it is too large, move right backward. This discards values that cannot produce the target.",
    deepExplanation: "Step 1 — WITHOUT BUILT-IN / CORE:\n```ts\nfunction twoSumSorted(\n  nums: readonly number[],\n  target: number,\n): [number, number] | null {\n  let left = 0;\n  let right = nums.length - 1;\n\n  while (left < right) {\n    const sum = nums[left]! + nums[right]!;\n\n    if (sum === target) {\n      return [left, right];\n    }\n\n    if (sum < target) left++;\n    else right--;\n  }\n\n  return null;\n}\n```\n\nWITH BUILT-IN:\n```ts\nfunction twoSumSortedUsingMap(\n  nums: readonly number[],\n  target: number,\n): [number, number] | null {\n  const positions = new Map<number, number>();\n\n  for (let i = 0; i < nums.length; i++) {\n    const needed = target - nums[i]!;\n\n    if (positions.has(needed)) {\n      return [positions.get(needed)!, i];\n    }\n\n    positions.set(nums[i]!, i);\n  }\n\n  return null;\n}\n```\n\nStep 2 — Example:\n[1,2,4,7,11], target=9\n1+11=12 → too large → right--\n1+7=8 → too small → left++\n2+7=9 → found [1,3].\n\nStep 3 — Complexity:\nTwo pointers O(n) time, O(1) extra.\nMap baseline O(n) average time, O(n) extra space.",
    productionExample: "Useful when datasets are stored in sorted order and pair queries are frequent. For unsorted data, a hash map is often a simpler choice.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "The pointer movement proof depends on sorted order."],
    tradeOffs: "| Method | Time | Extra Space |\n|---|---:|---:|\n| Two pointers | O(n) | O(1) |\n| Hash map | O(n) average | O(n) |\n| Brute force | O(n²) | O(1) |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How do you return values instead of indexes?", "What if duplicates are allowed?"],
    relatedTopics: ["Two Sum", "Two Pointers", "Hash Map", "Sorted Arrays"],
  },
  {
    id: "dsa-m14-134",
    number: "DSA-M14-134",
    title: "Three Sum",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Three Sum sorts the array, fixes one value, and uses opposite-direction pointers for the remaining two values. The main challenge is skipping duplicates while preserving O(n²) complexity.",
    deepExplanation: "Step 1 — Sort and reduce to Two Sum.\n\nWITHOUT BUILT-IN / CORE:\n```ts\nfunction threeSum(nums: readonly number[]): number[][] {\n  const values = [...nums].sort((a, b) => a - b);\n  const result: number[][] = [];\n\n  for (let i = 0; i < values.length - 2; i++) {\n    if (i > 0 && values[i] === values[i - 1]) continue;\n\n    let left = i + 1;\n    let right = values.length - 1;\n\n    while (left < right) {\n      const sum = values[i]! + values[left]! + values[right]!;\n\n      if (sum === 0) {\n        result.push([values[i]!, values[left]!, values[right]!]);\n\n        const leftValue = values[left]!;\n        const rightValue = values[right]!;\n\n        while (left < right && values[left] === leftValue) left++;\n        while (left < right && values[right] === rightValue) right--;\n      } else if (sum < 0) {\n        left++;\n      } else {\n        right--;\n      }\n    }\n  }\n\n  return result;\n}\n```\n\nWITH BUILT-IN:\n```ts\nfunction threeSumUsingSet(nums: readonly number[]): number[][] {\n  const values = [...nums].sort((a, b) => a - b);\n  const result: number[][] = [];\n\n  for (let i = 0; i < values.length - 2; i++) {\n    if (i > 0 && values[i] === values[i - 1]) continue;\n\n    const seen = new Set<number>();\n\n    for (let j = i + 1; j < values.length; j++) {\n      const needed = -values[i]! - values[j]!;\n\n      if (seen.has(needed)) {\n        result.push([values[i]!, needed, values[j]!]);\n        seen.delete(needed);\n      }\n\n      seen.add(values[j]!);\n    }\n  }\n\n  return result;\n}\n```\n\nStep 2 — Example:\n[-1,0,1,2,-1,-4]\n→ [-1,-1,2], [-1,0,1].\n\nStep 3 — Complexity:\nSorting O(n log n), two-pointer scan O(n²), so total O(n²).\nExtra working space excluding the output is O(1) beyond the copied/sorted input; the implementation copies input to avoid mutation.",
    productionExample: "Three-value matching appears in financial combinations, feature compatibility, coordinate constraints, and pair-plus-one-value searches.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Skip duplicate fixed values and duplicate left/right values after a match.", "Use a copied array when input mutation is not allowed."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| Sort + two pointers | O(n²), predictable | Sorting + duplicate logic |\n| Hash per fixed value | Similar time, flexible | O(n) extra per iteration |\n| Brute force | Simple | O(n³) |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How do you solve 4Sum?", "How do you avoid duplicate triplets?"],
    relatedTopics: ["Three Sum", "Two Pointers", "Sorting", "Hash Set"],
  },
  {
    id: "dsa-m14-135",
    number: "DSA-M14-135",
    title: "Container with most water",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Start at both ends. The area is width times the shorter height. Moving the taller boundary cannot improve the area while the shorter boundary remains, so move the shorter side inward.",
    deepExplanation: "Step 1 — WITHOUT BUILT-IN / CORE:\n```ts\nfunction maxArea(height: readonly number[]): number {\n  let left = 0;\n  let right = height.length - 1;\n  let best = 0;\n\n  while (left < right) {\n    const width = right - left;\n    const current = Math.min(height[left]!, height[right]!) * width;\n    best = Math.max(best, current);\n\n    if (height[left]! < height[right]!) {\n      left++;\n    } else {\n      right--;\n    }\n  }\n\n  return best;\n}\n```\n\nWITH BUILT-IN baseline:\n```ts\nfunction maxAreaBruteForce(height: readonly number[]): number {\n  let best = 0;\n\n  for (let left = 0; left < height.length - 1; left++) {\n    for (let right = left + 1; right < height.length; right++) {\n      const area =\n        Math.min(height[left]!, height[right]!) * (right - left);\n\n      best = Math.max(best, area);\n    }\n  }\n\n  return best;\n}\n```\n\nStep 2 — Example:\n[1,8,6,2,5,4,8,3,7]\nbest area = 49.\n\nStep 3 — Complexity:\nTwo pointers O(n) time, O(1) auxiliary space.\nBrute force O(n²).",
    productionExample: "The pattern is a classic interview greedy/two-pointer proof. In production, the same reasoning applies to boundary-pair optimization problems where one side limits the score.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Explicitly explain why moving the taller side cannot improve the current width-and-min-height product."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| Two pointers | O(n), O(1) | Requires greedy proof |\n| Brute force | Easy correctness | O(n²) |\n| Precomputation | Rarely useful here | Extra complexity |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "Why is moving the shorter side safe?", "How is this different from trapping rain water?"],
    relatedTopics: ["Two Pointers", "Greedy", "Arrays", "Optimization"],
  },
  {
    id: "dsa-m14-136",
    number: "DSA-M14-136",
    title: "Remove duplicates",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "For a sorted array, use a slow write pointer for the next unique position and a fast read pointer to scan values. Each new value that differs from the last written value is copied forward.",
    deepExplanation: "Step 1 — WITHOUT BUILT-IN / CORE:\n```ts\nfunction removeDuplicatesInPlace(nums: number[]): number {\n  if (nums.length === 0) return 0;\n\n  let write = 1;\n\n  for (let read = 1; read < nums.length; read++) {\n    if (nums[read] !== nums[write - 1]) {\n      nums[write] = nums[read]!;\n      write++;\n    }\n  }\n\n  return write;\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\nfunction removeDuplicatesUsingSet(nums: readonly number[]): number[] {\n  return [...new Set(nums)];\n}\n```\n\nStep 3 — Example:\n[1,1,2,2,3]\nafter in-place processing:\nfirst 3 positions = [1,2,3]\nreturned length = 3.\n\nStep 4 — Complexity:\nIn-place sorted-array version O(n) time, O(1) auxiliary space.\nSet version O(n) average time, O(n) extra space.\n\nImportant:\nThe two-pointer version depends on sorted input.",
    productionExample: "Useful for deduplicating sorted IDs, timestamps, event keys, and normalized datasets without allocating another full array.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Clearly state that duplicates must be adjacent because the input is sorted.", "Return the valid prefix length when using the classic in-place contract."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| In-place two pointers | O(1) extra | Requires sorted data |\n| Set | Simple and generic | Extra memory |\n| Sort + in-place | Handles unsorted values | O(n log n) + mutation/copy cost |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How do you allow each value twice?", "What if input is unsorted?"],
    relatedTopics: ["Two Pointers", "Sorted Arrays", "In-place Algorithms", "Set"],
  },
  {
    id: "dsa-m14-137",
    number: "DSA-M14-137",
    title: "Merge intervals with pointers",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "After sorting intervals by start time, scan from left to right and merge the current interval with the previous merged interval whenever they overlap.",
    deepExplanation: `Step 1 — Sort, then scan.\n\nWITHOUT BUILT-IN / CORE:\n\`\`\`ts\ntype Interval = [number, number];\n\nfunction mergeIntervals(intervals: readonly Interval[]): Interval[] {\n  if (intervals.length === 0) return [];\n\n  const sorted = intervals\n    .map(([start, end]) => [start, end] as Interval)\n    .sort((a, b) => a[0] - b[0]);\n\n  const result: Interval[] = [sorted[0]!];\n\n  for (let i = 1; i < sorted.length; i++) {\n    const current = sorted[i]!;\n    const last = result[result.length - 1]!;\n\n    if (current[0] <= last[1]) {\n      last[1] = Math.max(last[1], current[1]);\n    } else {\n      result.push(current);\n    }\n  }\n\n  return result;\n}\n\`\`\`\n\nWITH BUILT-IN:\n\`\`\`ts
type Interval = [number, number];

function mergeIntervalsUsingReduce(\n  intervals: readonly Interval[],\n): Interval[] {\n  const sorted = intervals\n    .map((interval) => [...interval] as Interval)\n    .sort((a, b) => a[0] - b[0]);\n\n  return sorted.reduce<Interval[]>((merged, current) => {\n    const last = merged[merged.length - 1];\n\n    if (!last || current[0] > last[1]) {\n      merged.push([...current] as Interval);\n    } else {\n      last[1] = Math.max(last[1], current[1]);\n    }\n\n    return merged;\n  }, []);\n}\n\`\`\`\n\nStep 2 — Example:\n[[1,3],[2,6],[8,10],[9,12]]\n→ [[1,6],[8,12]].\n\nStep 3 — Complexity:\nSorting O(n log n), merge scan O(n).\nTotal O(n log n); output space O(n).`,
    productionExample: "Useful for calendar conflicts, availability ranges, network time windows, deployment intervals, and UI timeline aggregation.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Copy intervals if the original objects/arrays must remain immutable.", "Sort only after clarifying that input order is not meaningful."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| Sort + scan | Simple and robust | O(n log n) sorting |\n| Ordered input | O(n) merge | Requires pre-sorted intervals |\n| Interval tree | Fast dynamic overlap queries | Much more complex |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How do you insert one interval?", "How do you detect overlaps without merging?"],
    relatedTopics: ["Two Pointers", "Intervals", "Sorting", "Sweep Line"],
  },
  {
    id: "dsa-m14-138",
    number: "DSA-M14-138",
    title: "Partitioning",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Partitioning rearranges a range so elements satisfying a predicate are moved to one side and the rest to the other. A two-pointer partition can do this in place with O(n) time and O(1) auxiliary space.",
    deepExplanation: "Step 1 — Partition negatives before non-negatives.\n\nWITHOUT BUILT-IN / CORE:\n```ts\nfunction partitionNegatives(nums: number[]): void {\n  let left = 0;\n  let right = nums.length - 1;\n\n  while (left <= right) {\n    while (left <= right && nums[left]! < 0) left++;\n    while (left <= right && nums[right]! >= 0) right--;\n\n    if (left < right) {\n      [nums[left], nums[right]] = [nums[right]!, nums[left]!];\n      left++;\n      right--;\n    }\n  }\n}\n```\n\nWITH BUILT-IN:\n```ts\nfunction partitionNegativesUsingFilter(\n  nums: readonly number[],\n): number[] {\n  return [\n    ...nums.filter((value) => value < 0),\n    ...nums.filter((value) => value >= 0),\n  ];\n}\n```\n\nStep 2 — Example:\n[-1,4,-3,2,0,-5]\nafter partition, every negative is before every non-negative.\nExact relative order is not guaranteed by the in-place partition.\n\nStep 3 — Complexity:\nIn-place version O(n) time, O(1) auxiliary space.\nFilter version O(n) time, O(n) extra space.",
    productionExample: "Partitioning is the core idea behind quicksort, filtering/compaction passes, and in-place categorization of buffers.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "State whether relative order must be preserved; ordinary partition is not stable."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| In-place partition | O(1) extra | Not necessarily stable |\n| filter/concat | Stable and readable | Extra memory |\n| Stable in-place partition | Preserves order | More complex and can be slower |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array.", "Assuming in-place partition preserves relative order."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How does partitioning power quicksort?", "How do you make partition stable?"],
    relatedTopics: ["Two Pointers", "Partition", "Quicksort", "In-place Algorithms"],
  },
  {
    id: "dsa-m14-139",
    number: "DSA-M14-139",
    title: "Fast and slow pointer relation",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Fast and slow pointers move at different speeds through a linked structure. If a cycle exists, the fast pointer eventually catches the slow pointer. The same technique can find the middle node or other relative positions.",
    deepExplanation: `Step 1 — Detect a linked-list cycle.\n\nWITHOUT BUILT-IN / CORE:\n\`\`\`ts\ninterface ListNode {\n  value: number;\n  next: ListNode | null;\n}\n\nfunction hasCycle(head: ListNode | null): boolean {\n  let slow = head;\n  let fast = head;\n\n  while (fast !== null && fast.next !== null) {\n    slow = slow!.next;\n    fast = fast.next.next;\n\n    if (slow === fast) return true;\n  }\n\n  return false;\n}\n\`\`\`\n\nWITH BUILT-IN:\n\`\`\`ts
interface ListNode {
  value: number;
  next: ListNode | null;
}

function hasCycleUsingSet(head: ListNode | null): boolean {\n  const seen = new Set<ListNode>();\n  let current = head;\n\n  while (current !== null) {\n    if (seen.has(current)) return true;\n    seen.add(current);\n    current = current.next;\n  }\n\n  return false;\n}\n\`\`\`\n\nStep 2 — Example:\n1 → 2 → 3 → 4\n          ↑     ↓\n          ←←←←←\nslow and fast eventually meet.\n\nStep 3 — Complexity:\nFloyd's algorithm O(n) time, O(1) auxiliary space.\nSet approach O(n) time, O(n) space.\n\nStep 4 — Extra use:\nThe same fast/slow relation can find the middle node by moving slow one step and fast two steps.`,
    productionExample: "Fast/slow pointers are useful for linked-list validation, cycle detection, stream-like pointer structures, and problems where one traversal needs to run at a different rate than another.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Compare node references, not node values, for cycle detection.", "Check fast.next before dereferencing fast.next.next."],
    tradeOffs: "| Method | Benefit | Cost |\n|---|---|---|\n| Floyd | O(1) extra space | Pointer logic is less obvious |\n| Set | Very easy to reason about | O(n) memory |\n| Index tracking | Useful for arrays | Not directly applicable to pointer cycles |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array.", "Comparing node values instead of references."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "How do you find the cycle entry?", "How do you find the middle node?", "Why does fast eventually meet slow?"],
    relatedTopics: ["Two Pointers", "Linked List", "Floyd Cycle Detection", "Fast/Slow Pointers"],
  },
  {
    id: "dsa-m14-140",
    number: "DSA-M14-140",
    title: "Two-pointer interview recognition",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Two Pointers",
    expectedAnswer: "Recognize two-pointer problems when two positions can advance through a sequence while maintaining an invariant, often because the data is sorted, a range is being compacted, or two traversal speeds provide useful information.",
    deepExplanation: "Step 1 — Recognition checklist:\n1. Is the input sorted or can it be sorted?\n2. Is the problem about a pair or a range?\n3. Can one pointer move forward while another moves backward or at the same speed?\n4. Can you prove that moving a pointer permanently eliminates candidates?\n5. Is the goal in-place compaction/partitioning?\n6. Is there a fast/slow relationship in a linked structure?\n\nStep 2 — WITHOUT BUILT-IN / CORE template:\n```ts\nfunction oppositePointerTemplate(\n  values: readonly number[],\n  target: number,\n): boolean {\n  let left = 0;\n  let right = values.length - 1;\n\n  while (left < right) {\n    const relation = values[left]! + values[right]!;\n\n    if (relation === target) return true;\n    if (relation < target) left++;\n    else right--;\n  }\n\n  return false;\n}\n```\n\nStep 3 — WITH BUILT-IN baseline:\n```ts\nfunction bruteForcePair(\n  values: readonly number[],\n  target: number,\n): boolean {\n  for (let i = 0; i < values.length - 1; i++) {\n    for (let j = i + 1; j < values.length; j++) {\n      if (values[i]! + values[j]! === target) return true;\n    }\n  }\n\n  return false;\n}\n```\n\nStep 4 — When NOT to use:\nDo not force two pointers onto unsorted data without another invariant, or onto problems where moving either pointer can discard a valid solution.\n\nTypical complexity:\nMany correct two-pointer scans are O(n), but sorting first changes the total to O(n log n).",
    productionExample: "This recognition skill is useful in coding interviews for pair sums, deduplication, interval processing, partitioning, and linked-list fast/slow problems.",
    bestPractices: ["State the pointer invariant before coding.", "Use the data-order property to justify pointer movement.", "Move pointers in a way that guarantees progress.", "Handle empty, one-element, duplicate, and boundary cases.", "State preprocessing cost separately when sorting or copying is required.", "Start from brute force, identify the repeated work, then prove exactly what one pointer movement eliminates."],
    tradeOffs: "| Pattern | Best for | Limitation |\n|---|---|---|\n| Two pointers | Ordered pair/range problems | Requires a valid invariant |\n| Hashing | Unsorted membership/pair lookup | Extra memory |\n| Sorting + pointers | Many pair/order problems | O(n log n) preprocessing |\n| Sliding window | Contiguous range constraints | Different invariant |",
    commonMistakes: ["Moving the wrong pointer without proving why.", "Off-by-one errors at left/right boundaries.", "Forgetting that sorted-input assumptions are required for many two-pointer solutions.", "Using two pointers when the data does not provide a monotonic decision.", "Claiming O(1) extra space while creating a copied/sorted array.", "Forcing two pointers onto a problem where pointer movement has no proof."],
    followUpQuestions: ["What is the pointer invariant?", "Why can one pointer move safely?", "What is the time complexity?", "What is the auxiliary-space complexity?", "When is sorting required?", "How do duplicates affect the result?", "What changes for unsorted input?", "Can hashing solve the same problem?", "How do you test boundary cases?", "When should two pointers not be used?", "Two pointers vs sliding window?", "Two pointers vs hashing?", "When does sorting first make sense?"],
    relatedTopics: ["Two Pointers", "Sliding Window", "Hashing", "Sorting", "Linked Lists"],
  },
];

export const MOCK_DSA_MODULE14_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    part: 'DSA',
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));