// Derived from frontend/src/document/DSA_Master_Handbook_Senior_Frontend_Engineers.md (Module 6 — Stack).
// Auto-generated by a one-off parser script from the handbook's per-topic template
// (Definition, JavaScript/TypeScript implementation, Time/Space Complexity,
// Trade-offs, Common Mistakes, Interview Tricks, Interview Questions).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Apple",
  "Netflix",
  "Uber",
  "Airbnb",
  "Atlassian",
  "Adobe",
  "LinkedIn",
  "Flipkart",
  "Zoho"
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "dsa-m6-51",
    number: "DSA-M6-51",
    title: "Stack fundamentals",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Stack fundamentals is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Stack fundamentals\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Stack fundamentals\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Stack fundamentals**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-52",
    number: "DSA-M6-52",
    title: "Valid parentheses",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Valid parentheses is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Valid parentheses\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Valid parentheses\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Valid parentheses**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-53",
    number: "DSA-M6-53",
    title: "Min stack",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Min stack is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Min stack\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Min stack\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Min stack**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-54",
    number: "DSA-M6-54",
    title: "Monotonic stack",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Monotonic stack is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Monotonic stack\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Monotonic stack\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Monotonic stack**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-55",
    number: "DSA-M6-55",
    title: "Next greater element",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Next greater element is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Next greater element\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Next greater element\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Next greater element**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-56",
    number: "DSA-M6-56",
    title: "Daily temperatures",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Daily temperatures is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Daily temperatures\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Daily temperatures\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Daily temperatures**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-57",
    number: "DSA-M6-57",
    title: "Expression evaluation",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Expression evaluation is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Expression evaluation\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Expression evaluation\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Expression evaluation**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-58",
    number: "DSA-M6-58",
    title: "Undo and redo",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Undo and redo is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Undo and redo\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Undo and redo\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Undo and redo**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-59",
    number: "DSA-M6-59",
    title: "Browser navigation stack",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Browser navigation stack is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Browser navigation stack\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Browser navigation stack\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Browser navigation stack**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m6-60",
    number: "DSA-M6-60",
    title: "Stack overflow and recursion",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Stack",
    expectedAnswer: "Stack overflow and recursion is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Stack overflow and recursion\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Stack overflow and recursion\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Stack overflow and recursion**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Stack","Time Complexity","Space Complexity","Pattern Recognition"],
  },
];

export const MOCK_DSA_MODULE6_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
