// Derived from frontend/src/document/DSA_Master_Handbook_Senior_Frontend_Engineers.md (Module 23 — Competitive Programming Basics).
// Auto-generated by a one-off parser script from the handbook's per-topic template
// (Definition, JavaScript/TypeScript implementation, Time/Space Complexity,
// Trade-offs, Common Mistakes, Interview Tricks, Interview Questions).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Apple",
  "Netflix",
  "Uber",
  "Airbnb",
  "Atlassian",
  "Adobe",
  "LinkedIn",
  "Flipkart",
  "Zoho"
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "dsa-m23-221",
    number: "DSA-M23-221",
    title: "Fast input and output",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Fast input and output is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Fast input and output\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Fast input and output\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Fast input and output**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-222",
    number: "DSA-M23-222",
    title: "Sorting",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Sorting is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Sorting\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Sorting\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Sorting**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-223",
    number: "DSA-M23-223",
    title: "Prefix and suffix techniques",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Prefix and suffix techniques is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Prefix and suffix techniques\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Prefix and suffix techniques\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Prefix and suffix techniques**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-224",
    number: "DSA-M23-224",
    title: "Coordinate compression",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Coordinate compression is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Coordinate compression\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Coordinate compression\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Coordinate compression**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-225",
    number: "DSA-M23-225",
    title: "Modular arithmetic",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Modular arithmetic is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Modular arithmetic\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Modular arithmetic\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Modular arithmetic**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-226",
    number: "DSA-M23-226",
    title: "GCD and LCM",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "GCD and LCM is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: GCD and LCM\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: GCD and LCM\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **GCD and LCM**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-227",
    number: "DSA-M23-227",
    title: "Sieve of Eratosthenes",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Sieve of Eratosthenes is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Sieve of Eratosthenes\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Sieve of Eratosthenes\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Sieve of Eratosthenes**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-228",
    number: "DSA-M23-228",
    title: "Combinatorics basics",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Combinatorics basics is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Combinatorics basics\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Combinatorics basics\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Combinatorics basics**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-229",
    number: "DSA-M23-229",
    title: "Bit tricks",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Bit tricks is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Bit tricks\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Bit tricks\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Bit tricks**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
  {
    id: "dsa-m23-230",
    number: "DSA-M23-230",
    title: "Contest strategy",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Competitive Programming Basics",
    expectedAnswer: "Contest strategy is an algorithm/data-structure/problem-solving concept used to transform, organize, search, traverse or schedule data efficiently.",
    deepExplanation: "JavaScript reference:\n\n```js\n// ES2024 — production-oriented reference implementation for: Contest strategy\nexport function solve(input) {\n  // Validate the public boundary before doing algorithmic work.\n  if (input == null) return null;\n\n  // Keep the algorithm deterministic and side-effect free where practical.\n  const data = Array.isArray(input) ? [...input] : input;\n\n  // Replace this placeholder with the topic-specific transformation.\n  return data;\n}\n\n// Complexity: depends on the chosen algorithm; always state it explicitly in an interview.\n```\n\nIntuition: Look for the smallest reusable rule that makes the next operation cheaper than recomputing everything.\n\n### Pattern recognition\n\nAsk:\n\n1. Is the data ordered?\n2. Is a contiguous range involved?\n3. Is a pair or pair-like relationship involved?\n4. Do I need membership or frequency lookup?\n5. Is this a hierarchical structure?\n6. Is the problem asking for a best value over states?\n7. Is there a local choice that can be proven safe?\n\n### When NOT to use it\n\nDo not use a pattern simply because it is familiar. If its invariant cannot be maintained, the data assumptions do not hold, or its memory cost dominates, choose another strategy.\n\nTime complexity: Always report complexity as a function of input size `n`.\n\nTypical targets:\n\n| Strategy | Typical Time |\n|---|---:|\n| Single traversal | O(n) |\n| Nested independent traversal | O(n²) |\n| Sorting | O(n log n) |\n| Hash lookup | O(1) average |\n| Binary search | O(log n) |\n| Tree traversal | O(n) |\n| Heap operation | O(log n) |\n\nSpace complexity: Distinguish **auxiliary space** from the memory required to store the input. In JavaScript, temporary arrays, object allocations, closures and copied strings can materially affect memory pressure.",
    productionExample: "TypeScript reference:\n\n```ts\n// TypeScript — strongly typed production boundary for: Contest strategy\nexport function solve<T>(input: readonly T[]): readonly T[] {\n  if (input.length === 0) return [];\n\n  // Prefer immutable inputs for reusable frontend utilities.\n  return [...input];\n}\n```",
    bestPractices: ["State the brute-force solution first.","Identify the bottleneck.","State the invariant before coding.","Explain why the optimization is correct.","Test an edge case before declaring completion.","State time and space complexity explicitly."],
    tradeOffs: "| Choice | Benefit | Cost |\n|---|---|---|\n| Hashing | Fast average lookup | Extra memory |\n| Sorting | Enables ordered techniques | O(n log n) preprocessing |\n| Recursion | Clear structure | Call-stack depth |\n| Iteration | Predictable stack usage | Sometimes more verbose |\n| Copying | Immutability | Allocation/GC cost |",
    commonMistakes: ["Off-by-one errors","Mutating input unexpectedly","Forgetting duplicate handling","Incorrect loop boundaries","Using `shift()` repeatedly on large arrays","Confusing reference equality with value equality","Ignoring recursion depth","Claiming O(1) hash lookup without stating average-case assumptions"],
    followUpQuestions: ["What is the core idea behind **Contest strategy**?","What invariant makes the algorithm correct?","What is the time complexity?","What is the auxiliary-space complexity?","What edge cases break a naive implementation?","Can the solution be made immutable?","What changes for streaming input?","What happens at very large scale?","Which alternative data structure could be used?","How would you test it?"],
    relatedTopics: ["Competitive Programming Basics","Time Complexity","Space Complexity","Pattern Recognition"],
  },
];

export const MOCK_DSA_MODULE23_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    part: 'DSA',
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
