// Derived from frontend/src/document/DSA_Master_Handbook_Senior_Frontend_Engineers.md (Module 19 — Frontend DSA Applications).
// Auto-generated by a one-off parser script from the handbook's per-topic template
// (Definition, JavaScript/TypeScript implementation, Time/Space Complexity,
// Trade-offs, Common Mistakes, Interview Tricks, Interview Questions).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  'Google',
  'Meta',
  'Amazon',
  'Microsoft',
  'Apple',
  'Netflix',
  'Uber',
  'Airbnb',
  'Atlassian',
  'Adobe',
  'LinkedIn',
  'Flipkart',
  'Zoho',
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};

const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "dsa-m19-181",
    number: "DSA-M19-181",
    title: "Autocomplete",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Autocomplete returns relevant suggestions for a typed prefix. A practical implementation keeps the search operation small, preserves result ranking, limits the number of returned items, and avoids repeated full-array scans when the dataset is large.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: keep normalized words and filter incrementally.\n```ts\ninterface Suggestion {\n  label: string;\n  score: number;\n}\n\nfunction autocomplete(\n  items: readonly Suggestion[],\n  query: string,\n  limit = 5,\n): Suggestion[] {\n  const normalized = query.trim().toLowerCase();\n\n  return items\n    .filter((item) => item.label.toLowerCase().startsWith(normalized))\n    .sort((a, b) => b.score - a.score)\n    .slice(0, limit);\n}\n```\n\nStep 2 — WITH BUILT-IN / production-friendly alternative: pre-sort once and keep immutable results.\n```ts\ninterface Suggestion {\n  label: string;\n  score: number;\n}\n\nfunction buildAutocompleteIndex(\n  items: readonly Suggestion[],\n): Suggestion[] {\n  return [...items].sort((a, b) => b.score - a.score);\n}\n\nfunction queryAutocomplete(\n  index: readonly Suggestion[],\n  query: string,\n  limit = 5,\n): Suggestion[] {\n  const normalized = query.trim().toLowerCase();\n  const result: Suggestion[] = [];\n\n  for (const item of index) {\n    if (item.label.toLowerCase().startsWith(normalized)) {\n      result.push(item);\n      if (result.length === limit) break;\n    }\n  }\n\n  return result;\n}\n```\n\nStep 3 — Example:\n`[\"apple\", \"application\", \"banana\"]`, query `\"app\"` → `[\"apple\", \"application\"]`.\n\nStep 4 — Complexity:\nSimple scan O(n·L) in the worst case, where L is text length.\nA Trie is preferable for very large/high-QPS prefix workloads.\nFrontend production usually also debounces input and cancels stale requests.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Use autocomplete for product search, command palettes, route search, code suggestions, and contact lookup. Debounce typing, cap results, and ignore stale async responses.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Normalize case consistently.", "Limit result count.", "Debounce network-backed queries.", "Do not let stale responses overwrite newer query results.", "Use a Trie or indexed backend for large datasets."],
    tradeOffs: "| Strategy | Benefit | Cost |\n|---|---|---|\n| Array scan | Simple | O(n) per query |\n| Trie | Fast prefix lookup | More memory |\n| Backend search index | Scales across large datasets | Network latency/complexity |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Sending a request on every keystroke without debounce.", "Ignoring stale responses.", "Sorting the full dataset on every keystroke.", "Returning too many suggestions."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How do you debounce input?", "How do you cancel stale requests?", "Trie vs array scan?", "How do you rank suggestions?", "How do you cache prefixes?", "How do you handle Unicode/case?", "How do you test rapid typing?", "How do you handle empty input?", "How do you scale to millions of terms?", "How do you avoid UI jank?"],
    relatedTopics: ["Autocomplete", "Trie", "Debounce", "Caching", "Search Ranking"],
  },
  {
    id: "dsa-m19-182",
    number: "DSA-M19-182",
    title: "Typeahead",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Typeahead is an interactive prediction pattern where the UI updates suggestions as the user types. The algorithmic problem is usually prefix matching plus request coordination, ranking, caching, and stale-response protection.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: keep a monotonic request id.\n```ts\nclass TypeaheadController {\n  private requestId = 0;\n\n  async search(\n    query: string,\n    fetcher: (query: string) => Promise<string[]>,\n  ): Promise<string[]> {\n    const currentId = ++this.requestId;\n    const result = await fetcher(query);\n\n    return currentId === this.requestId ? result : [];\n  }\n}\n```\n\nStep 2 — WITH BUILT-IN / array-only local search:\n```ts\nfunction localTypeahead(\n  values: readonly string[],\n  query: string,\n  limit = 8,\n): string[] {\n  const normalized = query.trim().toLowerCase();\n\n  return values\n    .filter((value) => value.toLowerCase().startsWith(normalized))\n    .slice(0, limit);\n}\n```\n\nStep 3 — Example:\nUser types `r`, then `re`, then `rea`.\nIf the `r` request finishes last, its result must not replace the `rea` suggestions.\n\nStep 4 — Complexity:\nLocal lookup O(n·L) worst case.\nRequest coordination is O(1) state per request.\nFor remote APIs, network latency dominates, so debounce/cache/cancellation matter more than micro-optimizing the loop.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Used in address search, command menus, global search, IDE-like inputs, and large forms with server-backed suggestions.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Debounce network requests.", "Use request ids or AbortController to prevent stale updates.", "Cache recent queries.", "Keep result limits small.", "Show loading/error/empty states explicitly."],
    tradeOffs: "| Technique | Benefit | Cost |\n|---|---|---|\n| Local filter | Instant | Client dataset memory |\n| Remote search | Large dataset | Network latency |\n| Cached remote | Faster repeated queries | Cache invalidation |\n| Trie | Fast prefix lookup | Memory/build cost |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Race conditions between requests.", "No loading state.", "Treating empty query as a normal expensive search.", "Unbounded cache growth."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How does AbortController help?", "How do you debounce?", "How do you cache by normalized query?", "How do you rank results?", "How do you handle offline mode?", "How do you test races?", "How do you prevent flicker?", "How do you prefetch likely next queries?", "How do you handle server pagination?", "How do you protect privacy?"],
    relatedTopics: ["Typeahead", "Debounce", "AbortController", "Caching", "Async UI"],
  },
  {
    id: "dsa-m19-183",
    number: "DSA-M19-183",
    title: "File explorer",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "A file explorer is naturally represented as a tree. Recursive rendering/traversal handles nested folders, while expansion state should usually be kept separately from the immutable file-tree data.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: flatten a tree for rendering or search.\n```ts\ninterface FileNode {\n  id: string;\n  name: string;\n  type: \"file\" | \"folder\";\n  children?: FileNode[];\n}\n\nfunction flattenFiles(root: FileNode): FileNode[] {\n  const result: FileNode[] = [];\n\n  function visit(node: FileNode): void {\n    result.push(node);\n    for (const child of node.children ?? []) visit(child);\n  }\n\n  visit(root);\n  return result;\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\ninterface FileNode {\n  id: string;\n  name: string;\n  type: \"file\" | \"folder\";\n  children?: FileNode[];\n}\n\nfunction findFileByName(\n  root: FileNode,\n  name: string,\n): FileNode | null {\n  if (root.name === name) return root;\n\n  return (\n    root.children\n      ?.map((child) => findFileByName(child, name))\n      .find((node): node is FileNode => node !== null) ?? null\n  );\n}\n```\n\nStep 3 — Example:\n`src → components → Button.tsx`\nA DFS visits `src`, `components`, then `Button.tsx`.\n\nStep 4 — Complexity:\nTraversal O(n), where n is the number of nodes.\nRecursive auxiliary space O(h), where h is tree depth.\nFor very deep trees, an explicit stack avoids call-stack limits.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Useful for IDE file trees, cloud-drive navigation, document managers, and nested settings/category explorers.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Keep tree data immutable.", "Store expanded node ids separately.", "Use stable ids/keys.", "Avoid traversing the entire tree for every small UI action.", "Virtualize very large visible trees."],
    tradeOffs: "| Approach | Benefit | Cost |\n|---|---|---|\n| Recursive tree | Natural | Deep recursion |\n| Explicit stack | Safe for deep trees | More code |\n| Normalized state | Fast id lookup | Reconstruction logic |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Using array indexes as stable node ids.", "Mutating nested state directly.", "Rendering every descendant of a huge collapsed tree.", "Ignoring deep-tree limits."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How do you toggle one folder immutably?", "How do you find a parent?", "How do you delete a subtree?", "How do you virtualize a tree?", "How do you store expansion state?", "How do stable React keys matter?", "What if nodes are shared?", "What if the data is loaded lazily?", "How do you search by filename?", "How do you preserve scroll position?"],
    relatedTopics: ["Trees", "DFS", "React", "Immutable State", "Virtualization"],
  },
  {
    id: "dsa-m19-184",
    number: "DSA-M19-184",
    title: "Nested comments",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Nested comments form a tree or forest. The typical frontend tasks are recursive rendering, flattening for virtualized lists, searching descendants, and immutable updates for one node or subtree.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: flatten nested comments in preorder.\n```ts\ninterface CommentNode {\n  id: string;\n  text: string;\n  replies: CommentNode[];\n}\n\nfunction flattenComments(root: readonly CommentNode[]): CommentNode[] {\n  const result: CommentNode[] = [];\n\n  function visit(node: CommentNode): void {\n    result.push(node);\n    for (const reply of node.replies) visit(reply);\n  }\n\n  for (const node of root) visit(node);\n  return result;\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\ninterface CommentNode {\n  id: string;\n  text: string;\n  replies: CommentNode[];\n}\n\nfunction countReplies(node: CommentNode): number {\n  return node.replies.reduce(\n    (total, reply) => total + 1 + countReplies(reply),\n    0,\n  );\n}\n```\n\nStep 3 — Example:\nA → B → C means A is shown first, then B, then C with increasing depth.\n\nStep 4 — Complexity:\nFlattening O(n).\nRecursive depth O(h).\nAvoid mutating the replies array when expanding/collapsing UI state.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Used for discussion threads, Reddit-like comments, issue conversations, feedback trees, and review threads.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Keep comment data separate from expanded/collapsed state.", "Use stable ids.", "Paginate or lazily load deep replies.", "Avoid recursive state mutation.", "Add depth limits or collapse behavior for extreme nesting."],
    tradeOffs: "| Design | Benefit | Cost |\n|---|---|---|\n| Nested tree | Natural rendering | Deep updates can be costly |\n| Flat normalized map | Fast lookup/update | More reconstruction |\n| Hybrid | Good UI performance | More state-management complexity |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Using array indexes as comment identity.", "Rebuilding the entire tree for every toggle.", "Rendering huge reply subtrees eagerly.", "Losing parent relationships when flattening."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How do you update one nested comment immutably?", "How do you find ancestors?", "How do you lazy-load replies?", "How do you virtualize comments?", "How do you preserve expanded state after refresh?", "How do you handle deleted parents?", "What if the tree contains cycles accidentally?", "How do you count descendants?", "How do you sort by score?", "How do you paginate each level?"],
    relatedTopics: ["Trees", "DFS", "Recursion", "Virtualization", "Immutable Updates"],
  },
  {
    id: "dsa-m19-185",
    number: "DSA-M19-185",
    title: "Virtualized list",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Virtualization renders only items near the viewport instead of every item. The core calculation maps scroll offset to a visible index range and renders an overscan buffer around it.",
    deepExplanation: `Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: fixed-height calculation.\n\`\`\`ts\ninterface VisibleRange {\n  start: number;\n  end: number;\n}\n\nfunction getVisibleRange(\n  scrollTop: number,\n  viewportHeight: number,\n  rowHeight: number,\n  itemCount: number,\n  overscan = 2,\n): VisibleRange {\n  if (itemCount === 0) return { start: 0, end: -1 };\n\n  const first = Math.floor(scrollTop / rowHeight);\n  const visibleCount = Math.ceil(viewportHeight / rowHeight);\n\n  return {\n    start: Math.max(0, first - overscan),\n    end: Math.min(itemCount - 1, first + visibleCount + overscan),\n  };\n}\n\`\`\`\n\nStep 2 — WITH BUILT-IN array helpers:\n\`\`\`ts
interface VisibleRange {
  start: number;
  end: number;
}

function visibleItems<T>(\n  items: readonly T[],\n  range: VisibleRange,\n): T[] {\n  return range.end < range.start\n    ? []\n    : items.slice(range.start, range.end + 1);\n}\n\`\`\`\n\nStep 3 — Example:\n100,000 rows, row height 40px, viewport 800px.\nOnly about 20 visible rows plus overscan need rendering, not 100,000.\n\nStep 4 — Complexity:\nRange calculation O(1).\nRendered work O(v), where v is visible + overscan items.\nMemory depends on virtualization strategy and item components.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.`,
    productionExample: "Virtualization is essential for large tables, feeds, chat histories, file lists, dashboards, and log viewers.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Use overscan to avoid blank gaps while scrolling.", "Keep stable keys.", "Measure row height accurately for fixed or variable-height strategies.", "Avoid expensive work in each visible row.", "Consider accessibility and keyboard navigation."],
    tradeOffs: "| Approach | Benefit | Cost |\n|---|---|---|\n| Render all | Simple | DOM/memory cost grows with n |\n| Fixed-height virtualization | Fast calculations | Requires stable row height |\n| Variable-height virtualization | Flexible | More measurement/cache complexity |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Rendering all 100k nodes and only hiding them with CSS.", "Using unstable keys.", "Incorrect scroll offset calculations.", "Ignoring variable row heights."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How do you virtualize variable-height rows?", "What is overscan?", "How do you preserve scroll position?", "How do you handle dynamic insertion?", "How do you test scrolling performance?", "How does virtualization affect accessibility?", "How do you combine it with memoization?", "What happens when row height changes?", "How do you implement reverse chat scrolling?", "When should you avoid virtualization?"],
    relatedTopics: ["Virtualization", "Scroll Position", "Trees", "Performance", "React"],
  },
  {
    id: "dsa-m19-186",
    number: "DSA-M19-186",
    title: "Undo redo editor",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Undo/redo is commonly modeled with two stacks: an undo stack for past states/actions and a redo stack for states undone most recently. A new edit clears redo history because the previous future branch is no longer valid.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE:\n```ts\nclass EditorHistory<T> {\n  private readonly undoStack: T[] = [];\n  private readonly redoStack: T[] = [];\n  private current: T;\n\n  constructor(initial: T) {\n    this.current = initial;\n  }\n\n  apply(next: T): void {\n    this.undoStack.push(this.current);\n    this.current = next;\n    this.redoStack.length = 0;\n  }\n\n  undo(): T {\n    const previous = this.undoStack.pop();\n    if (previous === undefined) return this.current;\n\n    this.redoStack.push(this.current);\n    this.current = previous;\n    return this.current;\n  }\n\n  redo(): T {\n    const next = this.redoStack.pop();\n    if (next === undefined) return this.current;\n\n    this.undoStack.push(this.current);\n    this.current = next;\n    return this.current;\n  }\n\n  value(): T {\n    return this.current;\n  }\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\nfunction undoRedoUsingArrays<T>(\n  history: readonly T[],\n  index: number,\n  direction: \"undo\" | \"redo\",\n): { value: T; index: number } {\n  const nextIndex =\n    direction === \"undo\"\n      ? Math.max(0, index - 1)\n      : Math.min(history.length - 1, index + 1);\n\n  return {\n    value: history[nextIndex]!,\n    index: nextIndex,\n  };\n}\n```\n\nStep 3 — Example:\nA → B → C\nundo → B\nundo → A\nredo → B\napply D after undo → redo history is cleared.\n\nStep 4 — Complexity:\nStack operations are O(1).\nMemory O(k) for stored history, where k is the number of retained states/actions.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Used in text editors, form builders, drawing apps, IDEs, workflow builders, and admin consoles.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Prefer storing reversible actions/deltas for large documents when possible.", "Cap history length or use checkpoints.", "Clear redo after a new branch of edits.", "Keep undo/redo transitions deterministic."],
    tradeOffs: "| Strategy | Benefit | Cost |\n|---|---|---|\n| Full state snapshots | Simple | Large memory |\n| Action/delta history | Lower memory | More complex reverse logic |\n| Hybrid checkpoints | Faster recovery | Extra bookkeeping |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Not clearing redo after a new edit.", "Mutating stored state snapshots.", "Storing giant documents for every keystroke.", "Mixing current-state and history-state ownership."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "Snapshot vs command history?", "How do you compress history?", "How do you implement undo for async operations?", "How do collaborative editors differ?", "How do you persist history?", "How do you cap memory?", "How do you test branching?", "How do you undo a batch of edits?", "How do you support transactions?", "What if the state is huge?"],
    relatedTopics: ["Stacks", "Command Pattern", "State History", "Immutable State"],
  },
  {
    id: "dsa-m19-187",
    number: "DSA-M19-187",
    title: "Browser history",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "Browser-style history can be modeled with a list plus a current cursor. Visiting a new URL truncates forward history; back and forward simply move the cursor within the retained entries.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE:\n```ts\nclass BrowserHistory {\n  private readonly entries: string[] = [];\n  private current = -1;\n\n  visit(url: string): void {\n    this.entries.splice(this.current + 1);\n    this.entries.push(url);\n    this.current = this.entries.length - 1;\n  }\n\n  back(): string | null {\n    if (this.current <= 0) return this.entries[0] ?? null;\n    this.current--;\n    return this.entries[this.current]!;\n  }\n\n  forward(): string | null {\n    if (this.current >= this.entries.length - 1) {\n      return this.entries[this.current] ?? null;\n    }\n    this.current++;\n    return this.entries[this.current]!;\n  }\n\n  currentUrl(): string | null {\n    return this.entries[this.current] ?? null;\n  }\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\nfunction truncateForwardHistory(history: readonly string[], current: number): string[] {\n  return history.slice(0, current + 1);\n}\n```\n\nStep 3 — Example:\nA → B → C\nback → B\nvisit D → A, B, D\nforward is no longer C.\n\nStep 4 — Complexity:\nWith Array.splice, truncation can be O(n) in the amount removed.\nBack/forward cursor movement is O(1).\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Useful for SPA route history, document navigation, tab stacks, wizard steps, and custom navigation state.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Use URL/history APIs for real browser navigation instead of recreating them without reason.", "Separate browser navigation state from component state.", "Consider memory limits for huge custom histories."],
    tradeOffs: "| Approach | Benefit | Cost |\n|---|---|---|\n| Cursor over array | Simple | Truncation/copy costs |\n| Two stacks | Simple back/forward semantics | Branch management |\n| Browser History API | Native navigation | Browser integration constraints |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Keeping forward history after a new visit.", "Using array indexes as persistent route identity.", "Duplicating native browser history unnecessarily."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "Two stacks vs cursor?", "How does replaceState differ from pushState?", "How do you preserve scroll position?", "How do you handle deep links?", "How do you test history branching?", "How do route guards interact?", "How do you serialize history?", "How do you cap custom history?", "What about multiple browser tabs?", "How do you handle back navigation with unsaved changes?"],
    relatedTopics: ["Stacks", "Routing", "History API", "State Management"],
  },
  {
    id: "dsa-m19-188",
    number: "DSA-M19-188",
    title: "Dependency graph viewer",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "A dependency graph viewer represents nodes and directed edges, then uses graph traversal to find dependencies, dependents, reachability, cycles, or a topological order for acyclic graphs.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: adjacency-list graph and DFS traversal.\n```ts\nfunction collectDependencies(\n  graph: ReadonlyMap<string, readonly string[]>,\n  start: string,\n): string[] {\n  const visited = new Set<string>();\n  const result: string[] = [];\n\n  function dfs(node: string): void {\n    if (visited.has(node)) return;\n    visited.add(node);\n\n    for (const dependency of graph.get(node) ?? []) {\n      dfs(dependency);\n    }\n\n    result.push(node);\n  }\n\n  dfs(start);\n  return result;\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\nfunction graphFromEdges(\n  edges: readonly [string, string][],\n): Map<string, string[]> {\n  const graph = new Map<string, string[]>();\n\n  for (const [from, to] of edges) {\n    const list = graph.get(from) ?? [];\n    list.push(to);\n    graph.set(from, list);\n  }\n\n  return graph;\n}\n```\n\nStep 3 — Example:\nA → B, A → C, B → D\nDependencies of A include B, D, C.\n\nStep 4 — Complexity:\nDFS O(V + E).\nAdjacency-list memory O(V + E).\nFor visualization, separately manage layout/rendering state from graph data.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Used for package dependency viewers, build graphs, import explorers, workflow DAGs, and service dependency dashboards.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Detect cycles explicitly when the graph is expected to be a DAG.", "Keep graph data normalized.", "Separate graph computation from layout/render state.", "Use memoization only for repeated queries with stable graph data."],
    tradeOffs: "| Technique | Benefit | Cost |\n|---|---|---|\n| DFS/BFS | O(V+E) traversal | Can be costly for huge graphs |\n| Topological sort | Dependency ordering | Requires DAG |\n| Layout algorithm | Visual readability | Expensive UI computation |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Assuming a dependency graph is acyclic without checking.", "Storing duplicate edges.", "Doing graph traversal during every render.", "Mixing graph identity with visual positions."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "How do you detect cycles?", "How do you topologically sort?", "DFS vs BFS?", "How do you compute affected descendants after a change?", "How do you virtualize large graphs?", "How do you lay out nodes?", "How do you memoize graph queries?", "How do you handle incremental updates?", "How do you avoid rendering all edges?", "How do you test cyclic input?"],
    relatedTopics: ["Graphs", "DFS", "BFS", "Topological Sort", "Visualization"],
  },
  {
    id: "dsa-m19-189",
    number: "DSA-M19-189",
    title: "Scheduler and task manager",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "A frontend scheduler manages queued work by priority, due time, or fairness. A priority queue is a natural structure when the highest-priority available task should be selected efficiently.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: simple priority queue with insertion order as a tie breaker.\n```ts\ninterface Task {\n  id: string;\n  priority: number;\n  createdAt: number;\n}\n\nclass TaskQueue {\n  private readonly tasks: Task[] = [];\n\n  add(task: Task): void {\n    this.tasks.push(task);\n    this.tasks.sort(\n      (a, b) => b.priority - a.priority || a.createdAt - b.createdAt,\n    );\n  }\n\n  take(): Task | undefined {\n    return this.tasks.shift();\n  }\n}\n```\n\nStep 2 — WITH BUILT-IN:\n```ts\ninterface Task {\n  id: string;\n  priority: number;\n  createdAt: number;\n}\n\nfunction sortTasks(tasks: readonly Task[]): Task[] {\n  return [...tasks].sort(\n    (a, b) => b.priority - a.priority || a.createdAt - b.createdAt,\n  );\n}\n```\n\nStep 3 — Example:\nTasks A(priority 1), B(priority 3), C(priority 2)\n→ B, C, A.\n\nStep 4 — Complexity:\nThe educational array queue uses O(n log n) sorting on every insertion and O(n) shift cost.\nFor production-scale dynamic scheduling, use a real min/max heap or a library priority queue.\nAlso consider starvation, cancellation, and browser main-thread limits.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Useful for background uploads, retry queues, analytics flushing, worker orchestration, autosave scheduling, and UI-priority task processing.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Define the scheduling objective first.", "Use a heap for scalable dynamic priority queues.", "Add cancellation and deadlines where appropriate.", "Prevent starvation with aging/fairness when necessary.", "Avoid long CPU tasks on the browser main thread."],
    tradeOffs: "| Strategy | Benefit | Cost |\n|---|---|---|\n| Sorted array | Simple | Expensive repeated reordering |\n| Heap | O(log n) add/pop | More implementation complexity |\n| FIFO queue | Fair/simple | No priority ordering |\n| Time-sliced scheduler | Better UI responsiveness | More coordination |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Calling `shift()` O(1).", "Ignoring starvation.", "Running long tasks synchronously on the main thread.", "Failing to cancel obsolete tasks."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "Heap implementation?", "How do you prevent starvation?", "How do you cancel queued work?", "Priority vs deadline?", "How do browser schedulers differ?", "How do you batch tasks?", "How do you test fairness?", "How do you handle retries?", "How do you avoid duplicate jobs?", "How do you measure scheduler latency?"],
    relatedTopics: ["Priority Queue", "Heap", "Scheduling", "Concurrency", "Web Workers"],
  },
  {
    id: "dsa-m19-190",
    number: "DSA-M19-190",
    title: "React reconciliation-oriented data structures",
    difficulty: "Hard",
    experienceLevel: "5–8 Years / 8+ Years",
    category: "Frontend DSA Applications",
    expectedAnswer: "For React-oriented DSA, stable identity and efficient lookup are key. Data is often normalized by id, while derived arrays are built for rendering; stable keys help React associate items across renders.",
    deepExplanation: "Step 1 — Understand the problem.\n\nStep 1 — WITHOUT BUILT-IN / CORE: normalize entities by id.\n```ts\ninterface Entity {\n  id: string;\n  name: string;\n}\n\ninterface EntityState {\n  byId: Record<string, Entity>;\n  ids: string[];\n}\n\nfunction addEntity(state: EntityState, entity: Entity): EntityState {\n  if (state.byId[entity.id]) return state;\n\n  return {\n    byId: {\n      ...state.byId,\n      [entity.id]: entity,\n    },\n    ids: [...state.ids, entity.id],\n  };\n}\n```\n\nStep 2 — WITH BUILT-IN Map:\n```ts\ninterface Entity {\n  id: string;\n  name: string;\n}\n\nfunction indexEntities(entities: readonly Entity[]): Map<string, Entity> {\n  return new Map(entities.map((entity) => [entity.id, entity]));\n}\n```\n\nStep 3 — Example:\nA list is reordered, but item ids stay stable, so the UI can preserve identity better than when array indexes are used as keys.\n\nStep 4 — Complexity:\nMap lookup O(1) average.\nImmutable object update above creates new objects/arrays, with cost proportional to copied structure.\nThe data structure supports efficient lookup; reconciliation itself remains the renderer's responsibility.\n\nStep 5 — Interview takeaway:\nUse the simplest implementation that preserves correctness and keeps UI work bounded.",
    productionExample: "Useful in normalized Redux/RTK state, large tables, caches, entity editors, and interfaces where items reorder, update independently, or need stable identity.",
    bestPractices: ["Start with the simplest correct data structure.", "State the invariant before coding.", "Keep identity stable with domain ids.", "Separate algorithmic state from UI rendering state.", "Measure performance before adding complexity.", "Use stable domain ids as React keys.", "Normalize large entity collections when random lookup is frequent.", "Memoize derived data when profiling shows repeated expensive computation.", "Do not claim a Map or normalization itself performs React reconciliation."],
    tradeOffs: "| Design | Benefit | Cost |\n|---|---|---|\n| Array of entities | Simple rendering | O(n) lookup |\n| Map/byId | Fast lookup | More normalized state |\n| Hybrid ids + byId | Fast lookup + ordered rendering | More update logic |\n| Index keys | Simple | Unstable identity during reordering |",
    commonMistakes: ["Using generic placeholder logic instead of the actual frontend algorithm.", "Mutating nested data unexpectedly.", "Using unstable array indexes as identity.", "Recomputing large structures on every render.", "Ignoring network races, cancellation, or main-thread cost.", "Using array indexes as keys for reorderable lists.", "Mutating normalized state directly.", "Recomputing large derived arrays on every render without measurement.", "Confusing data-structure optimization with React's internal reconciliation algorithm."],
    followUpQuestions: ["What is the invariant?", "What is the time complexity?", "What is the auxiliary-space complexity?", "What is the simplest alternative?", "When does this scale poorly?", "How do you test the edge cases?", "How do you optimize only after measurement?", "How does this behave with async data?", "What changes for very large datasets?", "How would you explain the trade-off in an interview?", "Why are stable keys important?", "Array vs Map for UI state?", "How do you update one entity immutably?", "When should state be normalized?", "How do you memoize selectors?", "How do you virtualize a normalized list?", "How do you handle optimistic updates?", "How do you preserve selection after sorting?", "How do you avoid unnecessary renders?", "How do you profile before optimizing?"],
    relatedTopics: ["React", "Normalization", "Map", "Stable Keys", "Memoization"],
  },
];

export const MOCK_DSA_MODULE19_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    part: 'DSA',
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));