// Derived from frontend/src/document/Frontend_Architecture_Design_Patterns_Enterprise_Development_Master_Handbook.md (Module 13 — Internationalization).
// Auto-generated by a one-off parser script from the handbook's per-topic template
// (Introduction/Definition, code examples, Advantages/Disadvantages, Best
// Practices, Common Mistakes/Anti-patterns, Interview Questions).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Netflix",
  "Adobe",
  "Atlassian",
  "Stripe",
  "Uber",
  "Flipkart",
  "Zoho"
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "arch-m13-1",
    number: "ARCH-M13-1",
    title: "i18next",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "i18next is an internationalization framework pattern for translation lookup, interpolation, pluralization, and locale-aware resource management. Keep translation keys stable and separate content from UI code.",
    deepExplanation: "Step 1 — Understand i18next.\n\ni18next is an internationalization framework pattern for translation lookup, interpolation, pluralization, and locale-aware resource management. Keep translation keys stable and separate content from UI code.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ntype LocaleMessage = Record<string, string>;\n\nfunction translate(\n  messages: LocaleMessage,\n  key: string,\n): string {\n  return messages[key] ?? `[missing:${key}]`;\n}\n\nconst messages = { greeting: \"Hello\" };\nconst text = translate(messages, \"greeting\");\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst messages = new Map([\n  [\"greeting\", \"Hello\"],\n]);\n\nconst text =\n  messages.get(\"greeting\") ?? \"[missing:greeting]\";\n```\n\nStep 3 — Production example:\nUse i18next at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use i18next at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-2",
    number: "ARCH-M13-2",
    title: "Localization",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Localization is the process of adapting text, number formats, dates, currency, and presentation rules to a locale. Internationalization provides the architecture; localization supplies locale-specific content and formatting.",
    deepExplanation: "Step 1 — Understand Localization.\n\nLocalization is the process of adapting text, number formats, dates, currency, and presentation rules to a locale. Internationalization provides the architecture; localization supplies locale-specific content and formatting.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ntype LocaleMessage = Record<string, string>;\n\nfunction translate(\n  messages: LocaleMessage,\n  key: string,\n): string {\n  return messages[key] ?? `[missing:${key}]`;\n}\n\nconst messages = { greeting: \"Hello\" };\nconst text = translate(messages, \"greeting\");\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst messages = new Map([\n  [\"greeting\", \"Hello\"],\n]);\n\nconst text =\n  messages.get(\"greeting\") ?? \"[missing:greeting]\";\n```\n\nStep 3 — Production example:\nUse Localization at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Localization at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-3",
    number: "ARCH-M13-3",
    title: "RTL",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "RTL support makes the UI work correctly in right-to-left languages. Prefer logical CSS properties and direction-aware icons instead of duplicating whole components.",
    deepExplanation: "Step 1 — Understand RTL.\n\nRTL support makes the UI work correctly in right-to-left languages. Prefer logical CSS properties and direction-aware icons instead of duplicating whole components.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ntype Direction = \"ltr\" | \"rtl\";\n\nfunction inlineStartProperty(\n  direction: Direction,\n): string {\n  return direction === \"rtl\"\n    ? \"margin-right\"\n    : \"margin-left\";\n}\n\nconst property = inlineStartProperty(\"rtl\");\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst direction = \"rtl\" as const;\nconst property =\n  direction === \"rtl\"\n    ? \"margin-inline-start\"\n    : \"margin-inline-start\";\n```\n\nStep 3 — Production example:\nUse RTL at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use RTL at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-4",
    number: "ARCH-M13-4",
    title: "ICU",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "ICU message syntax models plural/select rules and interpolation in a locale-aware way. It is preferable to manual string concatenation for complex messages.",
    deepExplanation: "Step 1 — Understand ICU.\n\nICU message syntax models plural/select rules and interpolation in a locale-aware way. It is preferable to manual string concatenation for complex messages.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ntype LocaleMessage = Record<string, string>;\n\nfunction translate(\n  messages: LocaleMessage,\n  key: string,\n): string {\n  return messages[key] ?? `[missing:${key}]`;\n}\n\nconst messages = { greeting: \"Hello\" };\nconst text = translate(messages, \"greeting\");\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst messages = new Map([\n  [\"greeting\", \"Hello\"],\n]);\n\nconst text =\n  messages.get(\"greeting\") ?? \"[missing:greeting]\";\n```\n\nStep 3 — Production example:\nUse ICU at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use ICU at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-5",
    number: "ARCH-M13-5",
    title: "Currency",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Currency formatting must use locale and currency rules instead of manual decimal and symbol concatenation.",
    deepExplanation: "Step 1 — Understand Currency.\n\nCurrency formatting must use locale and currency rules instead of manual decimal and symbol concatenation.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ninterface Money {\n  amount: number;\n  currency: string;\n}\n\nfunction moneyText(value: Money): string {\n  return value.currency + \" \" + value.amount.toFixed(2);\n}\n\nconst text = moneyText({\n  amount: 1250.5,\n  currency: \"INR\",\n});\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst formatter = new Intl.NumberFormat(\"en-IN\", {\n  style: \"currency\",\n  currency: \"INR\",\n});\n\nconst text = formatter.format(1250.5);\n```\n\nStep 3 — Production example:\nUse Currency at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Currency at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-6",
    number: "ARCH-M13-6",
    title: "Dates",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Dates should be represented consistently in application state and formatted at the presentation boundary using locale-aware APIs.",
    deepExplanation: "Step 1 — Understand Dates.\n\nDates should be represented consistently in application state and formatted at the presentation boundary using locale-aware APIs.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\nfunction formatDateParts(\n  year: number,\n  month: number,\n  day: number,\n): string {\n  return `${day}/${month}/${year}`;\n}\n\nconst text = formatDateParts(2026, 8, 24);\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst text = new Intl.DateTimeFormat(\n  \"en-IN\",\n  { dateStyle: \"medium\" },\n).format(new Date(\"2026-08-24\"));\n```\n\nStep 3 — Production example:\nUse Dates at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Dates at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-7",
    number: "ARCH-M13-7",
    title: "Dynamic Locales",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Dynamic locale switching requires a stable locale state, resource loading, fallback handling, and a safe UI refresh boundary.",
    deepExplanation: "Step 1 — Understand Dynamic Locales.\n\nDynamic locale switching requires a stable locale state, resource loading, fallback handling, and a safe UI refresh boundary.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ntype Locale = \"en\" | \"ta\";\n\ninterface LocaleStore {\n  current: Locale;\n  set(locale: Locale): void;\n}\n\nfunction createLocaleStore(\n  initial: Locale,\n): LocaleStore {\n  let current = initial;\n\n  return {\n    get current() {\n      return current;\n    },\n    set(locale) {\n      current = locale;\n    },\n  };\n}\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nlet currentLocale = \"en\";\n\nfunction setLocale(locale: \"en\" | \"ta\"): void {\n  currentLocale = locale;\n}\n\nsetLocale(\"ta\");\n```\n\nStep 3 — Production example:\nUse Dynamic Locales at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Dynamic Locales at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-8",
    number: "ARCH-M13-8",
    title: "Lazy Loading",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Lazy-loading translation resources reduces initial payload for applications with many locales, but loading failure and fallback behavior must be explicit.",
    deepExplanation: "Step 1 — Understand Lazy Loading.\n\nLazy-loading translation resources reduces initial payload for applications with many locales, but loading failure and fallback behavior must be explicit.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ninterface ResourceLoader {\n  load(locale: string): Promise<Record<string, string>>;\n}\n\nasync function loadLocale(\n  loader: ResourceLoader,\n  locale: string,\n): Promise<Record<string, string>> {\n  return loader.load(locale);\n}\n\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nasync function loadMessages(\n  locale: string,\n): Promise<Record<string, string>> {\n  const resources: Record<string, Record<string, string>> = {\n    en: { greeting: \"Hello\" },\n    ta: { greeting: \"வணக்கம்\" },\n  };\n\n  return Promise.resolve(\n    resources[locale] ?? resources.en,\n  );\n}\n```\n\nStep 3 — Production example:\nUse Lazy Loading at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Lazy Loading at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
  {
    id: "arch-m13-9",
    number: "ARCH-M13-9",
    title: "Enterprise Strategies",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Internationalization",
    expectedAnswer: "Enterprise internationalization needs shared key conventions, ownership, translation workflows, testing, locale governance, and release coordination.",
    deepExplanation: "Step 1 — Understand Enterprise Strategies.\n\nEnterprise internationalization needs shared key conventions, ownership, translation workflows, testing, locale governance, and release coordination.\n\nStep 2 — Easy method:\nIdentify the owner, define the smallest contract, implement the simplest path, then add the required operational safeguards.\n\nWITHOUT BUILT-IN / CORE TypeScript:\n```ts\ninterface LocaleConfig {\n  locale: string;\n  fallback: string;\n}\n\nfunction resolveLocale(\n  config: LocaleConfig,\n  requested: string,\n): string {\n  return requested || config.fallback;\n}\n\nconst locale = resolveLocale(\n  { locale: \"en-IN\", fallback: \"en\" },\n  \"\",\n);\n```\n\nWITH BUILT-IN / practical TypeScript:\n```ts\nconst supported = new Set([\"en\", \"ta\", \"hi\"]);\nconst requested = \"ta\";\nconst locale = supported.has(requested)\n  ? requested\n  : \"en\";\n```\n\nStep 3 — Production example:\nUse Enterprise Strategies at the internationalization boundary so locale-specific behavior stays out of ordinary business components.\n\nStep 4 — Edge cases:\nConsider invalid input, lifecycle cleanup, failure handling, compatibility, and observability at the boundary.\n\nStep 5 — Senior interview takeaway:\nExplain what problem the approach solves, what it does not solve, the simplest alternative, and the main production trade-off.",
    productionExample: "Use Enterprise Strategies at the internationalization boundary so locale-specific behavior stays out of ordinary business components.",
    bestPractices: ["Define the responsibility and public contract before choosing an implementation.", "Keep data or behavior ownership explicit and avoid hidden global coupling.", "Handle invalid input, failure, cleanup, and lifecycle boundaries.", "Prefer the smallest abstraction that solves the real problem.", "Add automated tests and operational checks for important behavior."],
    tradeOffs: "The abstraction improves consistency and locale support, but it adds translation/resource governance and testing cost.",
    commonMistakes: ["Using the concept because it sounds enterprise-grade instead of solving a concrete problem.", "Mixing responsibilities so business rules and infrastructure become inseparable.", "Ignoring edge cases, cleanup, compatibility, or security implications.", "Creating an abstraction before the change pattern is understood.", "Treating a sample implementation as production-complete without operational safeguards."],
    followUpQuestions: ["What problem does this concept solve?", "When would you use it?", "When would you avoid it?", "What is the source of truth or owner?", "How would you test it?", "What are the main failure modes?", "What is the performance impact?", "How would you migrate an existing system?", "How would you monitor it?", "What trade-off would you explain in a senior interview?"],
    relatedTopics: ["Internationalization"],
  },
];

export const MOCK_FRONTEND_ARCHITECTURE_MODULE13_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    part: 'Architecture',
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));