// Derived from frontend/src/document/Part_12_Frontend_Security_Master_Handbook.md (Module 11 — Clickjacking & UI Security).
// Auto-generated by a one-off parser script from the handbook's per-question template
// (Question/Definition, code examples, Best Practices, Advantages/Disadvantages,
// Common Mistakes/Interview Traps, Senior Follow-up Questions, Related Topics).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  companies: string[];
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "sec-m11-176",
    number: "SEC-M11-176",
    title: "Clickjacking",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Clickjacking** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-177",
    number: "SEC-M11-177",
    title: "Frame-ancestors",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Frame-ancestors** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-178",
    number: "SEC-M11-178",
    title: "X-Frame-Options",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**X-Frame-Options** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-179",
    number: "SEC-M11-179",
    title: "Iframe sandbox",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Iframe sandbox** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-180",
    number: "SEC-M11-180",
    title: "UI redressing",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**UI redressing** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-181",
    number: "SEC-M11-181",
    title: "Overlay attacks",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Overlay attacks** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-182",
    number: "SEC-M11-182",
    title: "Pointer interception",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Pointer interception** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-183",
    number: "SEC-M11-183",
    title: "Window.opener",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**Window.opener** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-184",
    number: "SEC-M11-184",
    title: "noopener",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**noopener** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
  {
    id: "sec-m11-185",
    number: "SEC-M11-185",
    title: "noreferrer",
    difficulty: "Medium",
    experienceLevel: "5–8 Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Airbnb"],
    category: "Clickjacking & UI Security",
    expectedAnswer: "**noreferrer** is a frontend security concern that must be evaluated across the browser, application, identity layer, API boundary, dependencies and production operations.",
    deepExplanation: "Example:\n\n```ts\n// Secure-by-default API wrapper: never interpolate secrets into URLs.\nexport async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, {\n    credentials: \"same-origin\",\n    headers: { Accept: \"application/json\" },\n  });\n\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json() as Promise<T>;\n}\n```\n\nProduction pattern:\n\n```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```\n\nWhy it matters: Prevents account compromise, data exposure and unauthorized actions. Reduces exploitable browser and supply-chain attack surface. Makes security controls reviewable, testable and observable.",
    productionExample: "```ts\n// Validate security-sensitive state at the boundary.\nfunction isAllowedOrigin(origin: string, allowed: readonly string[]) {\n  return allowed.includes(origin);\n}\n\nconsole.log(isAllowedOrigin(\"https://app.example.com\", [\n  \"https://app.example.com\",\n]));\n```",
    bestPractices: ["Prefer explicit, readable code."],
    tradeOffs: "Advantages: Reduced attack surface; Better separation of trust boundaries; Easier security testing; Stronger enterprise governance.",
    commonMistakes: ["Confusing CORS with authentication","Confusing encoding with authorization","Logging tokens or passwords","Assuming HTTPS prevents XSS","Treating JWT signing as permission enforcement"],
    followUpQuestions: ["What is the attacker capability?","What is the trust boundary?","What browser control can reduce the attack surface?","What must be enforced server-side?","How would you test the defense?","What telemetry would detect recurrence?","What is the migration strategy for legacy clients?"],
    relatedTopics: ["OWASP","OAuth 2.1","OIDC","PKCE","CSP","Trusted Types","SameSite","CORS","CSRF","XSS","Secure React","Supply Chain","SAST","DAST","---"],
  },
];

export const MOCK_FRONTEND_SECURITY_MODULE11_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: seed.companies,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
