// Derived from frontend/src/document/Part_4_Modules_15_to_28_Advanced_JavaScript_Master_Handbook.md (Module 28 — Final Revision).
// Auto-generated by a one-off parser script from the handbook's per-question template
// (Definition/Overview, Syntax/Core Example, Best Practices, Advantages/Disadvantages,
// Common Mistakes/Interview Traps, Senior Follow-up Questions, Related Topics).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

const COMPANIES = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Netflix",
  "Adobe",
  "Atlassian",
  "Stripe",
  "Uber",
  "Flipkart",
  "Zoho"
];

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "jsadv-m28-591",
    number: "JSADV-M28-591",
    title: "Execution Context Revision",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Final Revision",
    expectedAnswer: "Execution Context Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Execution Context Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-592",
    number: "JSADV-M28-592",
    title: "Closures Revision",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Final Revision",
    expectedAnswer: "Closures Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Closures Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-593",
    number: "JSADV-M28-593",
    title: "Event Loop Revision",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Final Revision",
    expectedAnswer: "Event Loop Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Event Loop Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-594",
    number: "JSADV-M28-594",
    title: "Promises Revision",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Final Revision",
    expectedAnswer: "Promises Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Promises Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-595",
    number: "JSADV-M28-595",
    title: "Async/Await Revision",
    difficulty: "Hard",
    experienceLevel: "5–8 Years",
    category: "Final Revision",
    expectedAnswer: "Async/Await Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Async/Await Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-596",
    number: "JSADV-M28-596",
    title: "Prototype Revision",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Final Revision",
    expectedAnswer: "Prototype Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Prototype Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-597",
    number: "JSADV-M28-597",
    title: "this Revision",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Final Revision",
    expectedAnswer: "this Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: this Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-598",
    number: "JSADV-M28-598",
    title: "Memory Revision",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Final Revision",
    expectedAnswer: "Memory Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Memory Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-599",
    number: "JSADV-M28-599",
    title: "Browser API Revision",
    difficulty: "Easy",
    experienceLevel: "0–2 Years",
    category: "Final Revision",
    expectedAnswer: "Browser API Revision is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Browser API Revision\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security"],
  },
  {
    id: "jsadv-m28-600",
    number: "JSADV-M28-600",
    title: "Final JavaScript Assessment",
    difficulty: "Medium",
    experienceLevel: "2–5 Years",
    category: "Final Revision",
    expectedAnswer: "Final JavaScript Assessment is an important JavaScript concept used to design, debug, optimize, or reason about production applications.",
    deepExplanation: "Core example:\n\n```js\n// Example for: Final JavaScript Assessment\\nconsole.log('Production-oriented example');\n```\n\nRuntime notes: ECMAScript defines the language semantics. Browsers provide host APIs such as DOM, timers, Fetch and storage. Node.js provides server-side APIs and its own event-loop integration. Do not confuse ECMAScript behavior with host API behavior.",
    bestPractices: ["Prefer explicit, readable code.","Handle failure paths deliberately.","Avoid hidden global state.","Keep functions small and testable.","Measure performance before optimizing.","Document non-obvious runtime behavior."],
    tradeOffs: "Advantages: Clear reasoning and predictable maintenance.; Better testability when boundaries are explicit.; Easier production debugging.. Disadvantages: Abstractions add complexity.; Optimizations can reduce readability.; Runtime-specific behavior can differ between browsers and Node.js..",
    commonMistakes: ["Assuming browser and Node.js behavior is identical.","Ignoring cleanup.","Overusing clever syntax.","Treating implementation details as ECMAScript guarantees.","Failing to test edge cases.","Interview trap: Explaining the result without explaining *why*.","Interview trap: Forgetting execution order.","Interview trap: Ignoring coercion or reference identity.","Interview trap: Confusing language features with browser APIs.","Interview trap: Giving a theoretical answer without a production trade-off."],
    followUpQuestions: ["What is the ECMAScript-level behavior?","Which parts are host/runtime-specific?","What happens in the browser?","What changes in Node.js?","What are the performance implications?","What edge cases can break the implementation?","How would you test it?","How would you monitor it in production?"],
    relatedTopics: ["Execution Context","Scope","Closures","Event Loop","Promises","Browser APIs","Memory Management","Performance","Security.\n\n\n---\n\n# Module 24 — Coding Master Section\n\nThe following coding problems should be solved in **two forms** whenever applicable:\n\n1. **Built-in / idiomatic solution**\n2. **Without the relevant built-in function**"],
  },
];

export const MOCK_JAVASCRIPT_ADVANCED_MODULE28_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: COMPANIES,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    part: 'Advanced JS',
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: `Work through the accompanying code example for "${seed.title}" and verify the documented output before generalizing the behavior to production code.`,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
