// Derived from frontend/src/document/Part_7_TypeScript_Master_Handbook.md (Module 19 — Senior TypeScript).
// Auto-generated by a one-off parser script from the handbook's per-question template
// (Question/Definition, code examples, Best Practices, Advantages/Disadvantages,
// Common Mistakes/Interview Traps, Senior Follow-up Questions, Related Topics).
// Mirrors the MockTechnicalQuestion shape defined in @/mocks/questions.

import type { MockTechnicalQuestion } from '@/mocks/questions';

interface QuestionSeed {
  id: string;
  number: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  experienceLevel: string;
  companies: string[];
  category: string;
  expectedAnswer: string;
  deepExplanation: string;
  productionExample: string;
  bestPractices: string[];
  tradeOffs: string;
  commonMistakes: string[];
  followUpQuestions: string[];
  relatedTopics: string[];
}

const FREQUENCY_BY_DIFFICULTY: Record<QuestionSeed['difficulty'], number> = {
  Easy: 5,
  Medium: 4,
  Hard: 3,
};


const QUESTION_SEEDS: QuestionSeed[] = [
  {
    id: "ts-m19-281",
    number: "TS-M19-281",
    title: "Large-scale type architecture",
    difficulty: "Medium",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Large-scale type architecture**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-282",
    number: "TS-M19-282",
    title: "API contracts",
    difficulty: "Hard",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **API contracts**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-283",
    number: "TS-M19-283",
    title: "Monorepo type sharing",
    difficulty: "Easy",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Monorepo type sharing**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-284",
    number: "TS-M19-284",
    title: "Enterprise domain types",
    difficulty: "Medium",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Enterprise domain types**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-285",
    number: "TS-M19-285",
    title: "Advanced generics at scale",
    difficulty: "Hard",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "Generics preserve relationships between input and output types without sacrificing reuse. Prefer constraints that express the minimum required capability.",
    deepExplanation: "Example:\n\n```ts\nfunction identity<T>(value: T): T {\n  return value;\n}\n\nconst result = identity<string>(\"TypeScript\");\nconsole.log(result); // TypeScript\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Advanced generics at scale**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-286",
    number: "TS-M19-286",
    title: "Type complexity trade-offs",
    difficulty: "Easy",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Type complexity trade-offs**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-287",
    number: "TS-M19-287",
    title: "Production compiler issues",
    difficulty: "Medium",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Production compiler issues**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-288",
    number: "TS-M19-288",
    title: "Migration from JavaScript",
    difficulty: "Hard",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Migration from JavaScript**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-289",
    number: "TS-M19-289",
    title: "Architecture governance",
    difficulty: "Easy",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Architecture governance**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---"],
  },
  {
    id: "ts-m19-290",
    number: "TS-M19-290",
    title: "Senior TypeScript interview scenario",
    difficulty: "Medium",
    experienceLevel: "8+ Years",
    companies: ["Google","Meta","Amazon","Microsoft","Netflix","Adobe","Atlassian","Stripe","Uber","Flipkart","Zoho"],
    category: "Senior TypeScript",
    expectedAnswer: "TypeScript adds static analysis to JavaScript. The key interview skill is explaining what the compiler can prove, what gets erased, what JavaScript runs at runtime, and how the type design scales in production.",
    deepExplanation: "Example:\n\n```ts\nconst name: string = \"TypeScript\";\nconst version: number = 5;\nconsole.log(name, version);\n```\n\nProduction pattern:\n\n```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```\n\nWhy it matters: Improves correctness before runtime. Makes APIs and component contracts explicit. Supports refactoring and large-team collaboration. Provides architectural documentation through types.",
    productionExample: "```ts\nconst count: number = 42;\n// const invalid: number = \"42\";\n// Error: Type 'string' is not assignable to type 'number'.\n```",
    bestPractices: ["Enable strict compiler settings.","Prefer `unknown` over `any` at trust boundaries.","Model domain invariants explicitly.","Keep shared types close to their owning domain.","Separate transport DTOs from domain models when transformations are needed."],
    tradeOffs: "Advantages: Stronger contracts and safer refactoring.; Better editor tooling.; Excellent fit for large React codebases.. Disadvantages: Type complexity can slow the compiler.; Types do not validate runtime data.; Poorly designed abstractions can become difficult to understand..",
    commonMistakes: ["Assuming TypeScript validates JSON at runtime.","Overusing `as` assertions.","Using `any` to silence compiler errors.","Creating excessively clever type-level abstractions.","Interview trap: Confusing compile-time types with runtime values.","Interview trap: Saying interfaces exist in emitted JavaScript.","Interview trap: Assuming all generic information exists at runtime.","Interview trap: Treating TypeScript as a replacement for runtime validation."],
    followUpQuestions: ["What does the compiler prove for **Senior TypeScript interview scenario**?","What JavaScript is emitted?","What happens at runtime?","How would you model the same concept in a monorepo?","How would you test the runtime boundary?","What trade-off appears at scale?"],
    relatedTopics: ["Generics","Interfaces","Type Aliases","Utility Types","Conditional Types","React + TypeScript","tsconfig","Runtime Validation","Monorepos","---","# Module 20 – Final Revision","**Questions 291–300**"],
  },
];

export const MOCK_TYPESCRIPT_MODULE19_TECHNICAL_QUESTIONS: MockTechnicalQuestion[] = QUESTION_SEEDS.map((seed) => ({
  detail: {
    id: seed.id,
    questionNumber: seed.number,
    title: seed.title,
    difficulty: seed.difficulty,
    companies: seed.companies,
    frequency: FREQUENCY_BY_DIFFICULTY[seed.difficulty],
    category: seed.category,
    concepts: seed.relatedTopics,
    solved: false,
    attempted: false,
    bookmarked: false,
    questionType: 'technical',
    experienceLevel: seed.experienceLevel,
    question: seed.title,
  },
  answer: {
    expectedAnswer: seed.expectedAnswer,
    deepExplanation: seed.deepExplanation,
    productionExample: seed.productionExample,
    bestPractices: seed.bestPractices,
    tradeOffs: seed.tradeOffs,
    commonMistakes: seed.commonMistakes,
    followUpQuestions: seed.followUpQuestions,
    relatedTopics: seed.relatedTopics,
  },
}));
